language: elixir

sudo: false

elixir:
  - 1.3.2
  - 1.4.5
  - 1.5.0

otp_release:
  - 18.2

script:
  - MIX_ENV=docs mix do deps.get, inch.report
  - MIX_ENV=test mix do deps.get, compile, coveralls.travis
