language: elixir
elixir:
  - 1.0.0
  - 1.0.2
otp_release:
  - 17.1
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix do deps.get, inch.report
  - MIX_ENV=test mix do deps.get, test && mix compile && mix coveralls.travis
